choralcat/urls.py
from typing import Union

from django.conf import settings
from django.contrib import admin
from django.urls import URLPattern, URLResolver, include, path
from django.views.defaults import page_not_found

URL = Union[URLPattern, URLResolver]
URLList = list[URL]

urlpatterns: URLList = [
    path("", include("choralcat.web.urls")),
    path("admin/", admin.site.urls),
    # path('admin/defender/', include('defender.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += [path("404/", page_not_found, {"exception": Exception("Example")})]

choralcat/web/models.py
import logging
import os
from datetime import timedelta
from typing import cast

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse

from choralcat.core.consts import VARCHAR_LENGTH
from choralcat.core.fields import AutoSlugField, UnidecodeField
from choralcat.core.models import CreatedUpdatedModel

logger = logging.getLogger(__name__)


class Organization(CreatedUpdatedModel):
    name = models.CharField(max_length=VARCHAR_LENGTH)
    slug = AutoSlugField(populated_from="name")

    def __str__(self) -> str:
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="profile")
    timezone = models.CharField(max_length=VARCHAR_LENGTH, default=settings.TIME_ZONE)
    organization = models.ForeignKey(Organization, on_delete=models.SET_NULL, null=True)


class Person(CreatedUpdatedModel):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=VARCHAR_LENGTH)
    last_name = models.CharField(max_length=VARCHAR_LENGTH, blank=True)
    slug = AutoSlugField(populated_from=["first_name", "last_name"])
    birth = models.DateField(null=True, blank=True)
    death = models.DateField(null=True, blank=True)
    bio = models.TextField(blank=True)
    poc = models.BooleanField(default=False)
    non_male_identifying = models.BooleanField(default=False)
    nationality = models.TextField(blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]
        verbose_name_plural = "People"

    def __str__(self) -> str:
        if self.last_name:
            return f"{self.last_name}, {self.first_name}"
        return self.first_name

    @property
    def name(self) -> str:
        if self.last_name:
            return f"{self.last_name}, {self.first_name}"
        return self.first_name

    def get_absolute_url(self) -> str:
        return reverse("person_detail", kwargs={"slug": self.slug})


class SimpleModel(CreatedUpdatedModel):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, null=True)
    value = models.CharField(max_length=VARCHAR_LENGTH, blank=True, unique=True, null=True)

    class Meta:
        ordering = ["value", "organization"]
        abstract = True

    def __str__(self) -> str:
        return self.value or ""


class Category(SimpleModel):
    class Meta:
        verbose_name_plural = "Categories"


class Instrument(SimpleModel):
    pass


class Topic(SimpleModel):
    pass


class Tag(SimpleModel):
    value = models.CharField(max_length=VARCHAR_LENGTH, blank=True, null=True)

    class Meta:
        unique_together = ("organization", "value")


class Composition(CreatedUpdatedModel):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=VARCHAR_LENGTH)
    title_unidecode = UnidecodeField(populated_from="title", max_length=VARCHAR_LENGTH)
    slug = AutoSlugField(populated_from="title")
    composers = models.ManyToManyField(Person, related_name="composers", blank=True)
    arrangers = models.ManyToManyField(Person, related_name="arrangers", blank=True)
    duration = models.DurationField(null=True, blank=True)
    starting_key = models.CharField(max_length=VARCHAR_LENGTH, blank=True)
    ending_key = models.CharField(max_length=VARCHAR_LENGTH, blank=True)
    time_period = models.CharField(max_length=VARCHAR_LENGTH, blank=True)
    language = models.CharField(max_length=VARCHAR_LENGTH, blank=True)
    number_of_voices = models.IntegerField(validators=[MinValueValidator(1)], blank=True, null=True)
    voicing = models.CharField(max_length=VARCHAR_LENGTH, blank=True)
    categories = models.ManyToManyField(Category, blank=True)
    accompaniment = models.ManyToManyField(Instrument, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    topics = models.ManyToManyField(Topic, blank=True)

    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)], blank=True, null=True)
    score_link = models.CharField(max_length=VARCHAR_LENGTH, blank=True)
    notes = models.TextField(blank=True)
    edition_notes = models.TextField(blank=True)

    class Meta:
        ordering = ["title"]

    def __str__(self) -> str:
        return self.title

    @property
    def duration_mmss(self) -> str:
        if not self.duration:
            return ""
        sec = self.duration.total_seconds()
        return f"{int(sec / 60):02d}:{int(sec % 60):02d}"

    @property
    def stars(self) -> range:
        return range(self.rating or 0)

    def get_absolute_url(self) -> str:
        return reverse("composition_detail", kwargs={"slug": self.slug})

    @property
    def has_score_attachment(self) -> bool:
        try:
            _ = self.score_attachment
            return True
        except CompositionScore.DoesNotExist:
            return False


class Program(CreatedUpdatedModel):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=VARCHAR_LENGTH)
    slug = AutoSlugField(populated_from="title")
    compositions = models.ManyToManyField(Composition, blank=True)
    ordering = models.JSONField(default=dict, blank=True)
    season = models.CharField(max_length=VARCHAR_LENGTH, blank=True)
    topics = models.ManyToManyField(Topic, blank=True)

    class Meta:
        ordering = ["season", "title"]

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self) -> str:
        return reverse("program_detail", kwargs={"slug": self.slug})

    @property
    def duration(self) -> timedelta:
        return cast(timedelta, self.compositions.aggregate(models.Sum("duration"))["duration__sum"])

    @property
    def compositions_ordered(self) -> list[Composition]:
        if self.ordering.get("compositions") is None:
            logger.warning(f"No composition ordering was found for {self}")

        slug_to_comp = {c.slug: c for c in self.compositions.all()}
        slugs = list(slug_to_comp.keys())
        ordering = self.ordering.get("compositions", [])
        if set(slugs) - set(ordering):
            logger.warning(
                f"Not all compositions were found in ordering for program {self}, defaulting to alphabetical order"
            )
            ordering = sorted(slugs)
            self.ordering["compositions"] = ordering
            self.save()
        return [slug_to_comp[slug] for slug in ordering]

    def add(self, composition: Composition) -> None:
        logger.info(f"Adding {composition} to program {self}")
        self.compositions.add(composition)
        if "compositions" not in self.ordering:
            logger.warning("Composition ordering was uninstantiated")
            self.ordering["compositions"] = [composition.slug]
        else:
            self.ordering["compositions"].append(composition.slug)

    def remove(self, composition: Composition) -> None:
        logger.info(f"Removing {composition} from program {self}")
        self.compositions.remove(composition)
        self.ordering["compositions"] = [c for c in self.ordering["compositions"] if c != composition.slug]

    def reorder(self, new_order: list[str]) -> None:
        logger.info(f"Reordering program {self} to {new_order}")
        self.ordering["compositions"] = new_order


class Attachment(models.Model):
    file = models.FileField()
    name = models.CharField(max_length=VARCHAR_LENGTH)

    class Meta:
        abstract = True

    def __str__(self) -> str:
        return self.name

    @property
    def extension(self) -> str:
        _, extension = os.path.splitext(self.file.name)
        return str(extension)


class CompositionAttachment(Attachment):
    composition = models.ForeignKey(Composition, on_delete=models.CASCADE, related_name="attachment")


class CompositionScore(Attachment):
    composition = models.OneToOneField(Composition, on_delete=models.CASCADE, related_name="score_attachment")

choralcat/web/templates/web/catalog/catalog.html
{% extends "web/base.html" %}

{% load static %}
{% load choralcat_components %}

{% block title %} - Catalog{% endblock %}

{% block main %}
  {% url "composition_new" as location %}
  {% table_header_with_action text="Catalog" action_text="New Composition" location=location %}

  {% include "partials/catalog/search_bar.html" %}

  {% include "partials/catalog/filters.html" %}
  <div x-data="{
      modalOpen: false,
      open(piece) {
        this.modalOpen = true;
        this.piece = piece;
      },
      piece: '',
    }">
    <div id="search-results">
      {% include "partials/catalog/table_with_pagination.html" %}
    </div>

    {% include "partials/program_modal/modal_base.html" %}
  </div>
{% endblock %}

choralcat/web/templates/web/catalog/catalog_form.html
{% load choralcat_components %}
{{ form.non_field_errors }}
<div>
  <div>
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      Composition
    </h3>
  </div>
  <div class="mt-3">
    {% text_input label="Title" field=form.title %}
  </div>
  <div class="mt-3 grid grid-cols-1 sm:grid-cols-6 gap-y-6 gap-x-4 ">
    {% text_input label="Composers" field=form.composers %}
    {% text_input label="Arrangers" field=form.arrangers %}
  </div>
  <div class="mt-3 grid grid-cols-1 sm:grid-cols-6 gap-y-6 gap-x-4 ">
    {% tag_input label="Categories" field=form.categories %}
    {% tag_input label="Topics" field=form.topics %}
  </div>
  <div class="mt-3 grid grid-cols-1 sm:grid-cols-6 gap-y-6 gap-x-4 ">
    {% tag_input label="Tags" field=form.tags %}
    {% tag_input label="Accompaniment" field=form.accompaniment %}
  </div>
  <div class="mt-3 grid grid-cols-1 sm:grid-cols-9 gap-y-6 gap-x-4 ">
    {% text_input label="Starting key" field=form.starting_key %}
    {% text_input label="Ending key" field=form.ending_key %}
    {% text_input label="Voicing" field=form.voicing %}
  </div>
  <div class="mt-3 grid grid-cols-1 sm:grid-cols-6 gap-y-6 gap-x-4">
    {% text_input label="Duration" field=form.duration %}
    {% text_input label="Number of voices" field=form.number_of_voices %}
  </div>
  <div class="mt-3 grid grid-cols-1 sm:grid-cols-9 gap-y-6 gap-x-4 ">
    {% text_input label="Time period" field=form.time_period %}
    {% text_input label="Language" field=form.language %}
    {% text_input label="Rating" field=form.rating %}
  </div>
  <div class="mt-3 grid grid-cols-1 gap-y-6 gap-x-4 ">
    {% text_input label="Score link" field=form.score_link %}
  </div>
  <div class="mt-3 grid grid-cols-1 gap-y-6 gap-x-4">
    {% text_input label="Notes" field=form.notes %}
    {% text_input label="Edition notes" field=form.edition_notes %}
  </div>
</div>

choralcat/web/templates/web/catalog/composition_create.html
{% extends "web/base.html" %}

{% load choralcat_components %}

{% block main %}
  <form action="{% url 'composition_new' %}" method="post">
    {% csrf_token %}
    <div class="space-y-8 divide-y divide-gray-200">
      {{ form }}
      <div class="pt-5">
        <div class="flex justify-end">
          {% url 'catalog' as back_url %}
          {% form_cancel_button label="Cancel" url=back_url %}
          {% form_action_button label="Create" %}
        </div>
      </div>
    </div>
  </form>
{% endblock %}

choralcat/web/templates/web/catalog/composition_detail.html
{% extends "web/base.html" %}

{% load static %}
{% load choralcat_components %}
{% load choralcat_extras %}

{% block main %}
  <div>
    <div class="lg:flex lg:items-center lg:justify-between" x-data="{
    modalOpen: false,
    open(piece) {
      this.modalOpen = true;
      this.piece = piece;
    },
    piece: '',
  }">
      <div class="flex-1 min-w-0">
        <h2 class="text-3xl font-header leading-7 text-gray-900">
          {{ composition.title }}
        </h2>
        <div class="mt-1 flex flex-col flex-wrap mt-0 pt-2">
          {% if composition.composers.count > 0 %}
            <div class="flex items-center text-gray-500">
              <span class="font-light">Composed by: &nbsp;</span>
              {% for composer in composition.composers.all %}
                <a class="text-primary hover:text-primary300"
                   href="{% url 'person_detail' composer.slug %}">
                  {{ composer }}{% if not forloop.last %};{% endif %}</a>
              {% endfor %}
            </div>
          {% endif %}
          {% if composition.arrangers.count > 0 %}
            <div class="flex items-center text-gray-500">
              <span class="font-light">Arranged by: &nbsp;</span>
              {% for arranger in composition.arrangers.all %}
                <a class="text-primary hover:text-primary300"
                   href="{% url 'person_detail' arranger.slug %}">
                  {{ arranger }}{% if not forloop.last %};{% endif %}</a>
              {% endfor %}
            </div>
          {% endif %}
          {% if composition.rating %}
            <div class="text-lg flex items-center mt-1 text-yellow-300">
              {% for _ in composition.stars %}
                {% star_icon "h-5 w-5" %}
              {% endfor %}
            </div>
          {% endif %}
        </div>
      </div>
      <div class="mt-5 flex lg:mt-0 lg:ml-4">
    <span class="hidden sm:block">
      <a href="{% url 'composition_edit' composition.slug %}"
         class="inline-flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        <!-- Heroicon name: solid/pencil -->
        {% pencil_icon "-ml-1 mr-2 h-5 w-5 text-gray-500" %}
        Edit
      </a>
    </span>
        <span class="sm:ml-3">
      <button type="button"
              class="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              @click="open('{{ composition.slug }}')"
              hx-get="{% url 'catalog_modal' composition.slug %}"
              hx-target="#modalContent">
        <!-- Heroicon name: solid/check -->
        {% plus_icon "w-5 h-5 -ml-1 mr-2" %}
        Add
      </button>
    </span>
      </div>
      {% include "partials/program_modal/modal_base.html" %}
    </div>
    <div class="mt-2 grid grid-flow-row text-gray-500">
      <div class="grid grid-cols-2">
        <div>
          {% if composition.time_period or composition.language %}
            <p>{% if composition.time_period %}
              {{ composition.time_period }}{% endif %}{% if composition.time_period and composition.language %}
              ,{% endif %}
              {% if composition.language %}{{ composition.language }}{% endif %}
            </p>
          {% endif %}
          {% if composition.tags.count %}
            <div><span class="mr-2 font-light text-gray-500">Tags:</span>
              {% for tag in composition.tags.all %}{% tag tag.value %}{% endfor %}
            </div>
          {% endif %}
          {% if composition.categories.count %}
            <div class="mt-1"><span class="mr-2 font-light text-gray-500">Categories:</span>
              {% for category in composition.categories.all %}{% tag category.value %}{% endfor %}
            </div>
          {% endif %}
          {% if composition.topics.count %}
            <div class="mt-1"><span class="mr-2 font-light text-gray-500">Topics:</span>
              {% for topic in composition.topics.all %}{% tag topic.value %}{% endfor %}
            </div>
          {% endif %}
        </div>
        <div class="grid justify-items-end text-gray-600">
          <div>{% for instrument in composition.accompaniment.all %}{% tag instrument.value %}{% endfor %}</div>
          {% if composition.number_of_voices %}
            <div class="inline-flex mt-1">
              <p>{{ composition.number_of_voices }} voices</p>
            </div>
          {% endif %}
          {% if composition.voicing %}
            <div class="inline-flex mt-1">
              <p>{{ composition.voicing }}</p>
            </div>
          {% endif %}
          <div class="mt-1 inline-flex items-center">
            {% if composition.duration %}
              {% clock_icon "flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" %}
              <p>
                {{ composition.duration_mmss }}
              </p>
            {% endif %}
          </div>
          <div class="inline-flex items-center mt-1">
            {% if composition.starting_key or composition.ending_key %}
              {% music_notes_icon "flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" %}
              <p>{{ composition.starting_key }}/{{ composition.ending_key }}</p>
            {% endif %}
          </div>
        </div>
      </div>
      {% if composition.score_link %}
        <div class="mt-2">
          <p><a class="text-primary hover:text-primary300" href="{{ composition.score_link }}">Score PDF</a></p>
        </div>
      {% endif %}

      {% score_upload composition %}

      {% if composition.notes or composition.edition_notes %}
        <hr class="mt-4 mb-4"/>
        <div class="mt-2">
          {% if composition.notes %}
            <div>
              <h4 class="text-xl font-header text-gray-800">Notes:</h4>
              <p>{{ composition.notes }}</p>
            </div>
          {% endif %}
          {% if composition.edition_notes %}
            <div class="mt-2">
              <h4 class="text-xl font-header text-gray-800">Edition Notes:</h4>
              <p>{{ composition.edition_notes }}</p>
            </div>
          {% endif %}
        </div>
      {% endif %}
      {% if composition.program_set.count %}
        <hr class="mt-4 mb-4"/>
        <h4 class="text-xl font-header text-gray-800">Contained in:</h4>
        <!-- This example requires Tailwind CSS v2.0+ -->
        <div class="flex flex-col mt-2">
          <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
              <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                  <thead class="bg-gray-50">
                  <tr>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Title
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Season
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Last Updated
                    </th>
                    <th scope="col" class="relative px-6 py-3">
                    </th>
                  </tr>
                  </thead>
                  <tbody class="bg-white divide-y divide-gray-200">

                  {% for program in composition.program_set.all %}
                    {% include "web/program/table_row.html" with show_edit=False %}
                  {% endfor %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

choralcat/web/templates/web/catalog/composition_edit.html
{% extends "web/base.html" %}

{% load choralcat_components %}

{% block main %}
  <form action="{% url 'composition_edit' composition.slug %}" method="post">
    {% csrf_token %}
    <div class="space-y-8 divide-y divide-gray-200">
      {{ form }}
      <div class="pt-5">
        <div class="flex justify-end">
          {% url 'composition_detail' composition.slug as back_url %}
          {% form_cancel_button label="Cancel" url=back_url %}
          {% form_action_button label="Save" %}
        </div>
      </div>
    </div>
  </form>
{% endblock %}

choralcat/web/templates/web/catalog/composition_score_upload.html
<form method="post" action="{% url 'catalog_file_upload' composition.slug %}" method="post">>
  {% csrf_token %}
  <input type="file" name="file">
  <input type="submit" id="submit" value="upload">
</form>